### ISSUE TITLE
Error non-zero exit status 132

### ISSUE THREAD

**Issue by alexxjss** [kavonrtep/TideCluster#1]
Hi Petr,

I have tried running tidecluster both using our regular /tmp (which didn't have enough space), redirecting it to another path, and using different machines to test if the problem was the server I was using. 

This is the command `nohup env TMPDIR=/path/TideCluster/tmp TideCluster.py tidehunter -c 10 -f /path/Lcuzxy.fa -pr Lcuzxy &`
and in all runs I keep getting the same error:

`
Illegal instruction
running TideHunter
TideHunter -f 2 -o /isilon/users/alex/programs/TideCluster/tmp/tmps6j63eb9.out -p 40 -P 3000 -c 5 -e 0.25 -t 10  /isilon/users/alex/programs/TideCluster/tmp/tmps6j63eb9
Traceback (most recent call last):
  File "/home/alex/miniconda3/envs/tidecluster/bin/TideCluster.py", line 641, in <module>
    tidehunter(
  File "/home/alex/miniconda3/envs/tidecluster/bin/TideCluster.py", line 395, in tidehunter
    results = tc.run_tidehunter(
              ^^^^^^^^^^^^^^^^^^
  File "/home/alex/miniconda3/envs/tidecluster/share/tidecluster/tc_utils.py", line 585, in run_tidehunter
    subprocess.check_call(tidehunter_cmd, shell=True)
  File "/home/alex/miniconda3/envs/tidecluster/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'TideHunter -f 2 -o /isilon/users/alex/programs/TideCluster/tmp/tmps6j63eb9.out -p 40 -P 3000 -c 5 -e 0.25 -t 10 /isilon/users/alex/programs/TideCluster/tmp/tmps6j63eb9' returned non-zero exit status 132. 
`

Do you know what could be causing the error?

Thanks

**Comment by kavonrtep** [comment]
Hi Alex, Can you share with me input data so I can reproduce this issue?
Petr

**Comment by kavonrtep** [comment]
Hi Alex, It is a problem with TideHunter package, can you try to install TideCluster using command:
```
mamba create -n tidecluster -c conda-forge  -c petrnovak -c bioconda  tidecluster
```
order of channels is important to ensure that TideHuner is installed from my channel
 Let me know if anything change
Petr

**Comment by alexxjss** [comment]
Hi Petr. I removed the previous installation and did a new one, but I still get the same error, which happens when Tidehunter starts running.
Thanks

**Comment by kavonrtep** [comment]
Hi Alex, can you try to compile TideHunter  from source. In activated TideCluster environment run:
``` bash
wget https://github.com/yangao07/TideHunter/releases/download/v1.4.3/TideHunter-v1.4.3.tar.gz
tar -zxvf TideHunter-v1.4.3.tar.gz && cd TideHunter-v1.4.3
make
cp bin/TideHunter $CONDA_PREFIX/bin
```
let me know if it works
Petr

**Comment by alexxjss** [comment]
Hi Petr, it worked!! Thanks
